version: "3.11"
services:

  webapp:
    build:
      context: ../ # Specify parent folder as context
      dockerfile: Docker/Dockerfile # Path to Dockerfile
    volumes:
      - ../:/app # Mount parent folder as volume
    ports:
     - "8501:8501"